In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN','londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )','12. Air France', '"Swiss Air"'],
'Pclas':[1,2,3,1,2]})

In [17]:
df.head()

From_To  FlightNumber  RecentDelays              Airline  Pclas
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)      1
1      MAdrid_miLAN           NaN            []    <Air France> (12)      2
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )      3
3    Budapest_PaRis           NaN          [13]       12. Air France      1
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"      2

### Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
x = labelencoder.fit_transform(df['Airline'])

In [9]:
x

array([4, 3, 1, 2, 0])

In [11]:
x = x.reshape(-1,1)

### One-Hot Encoding

In [12]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
y = onehotencoder.fit_transform(x).toarray()

In [13]:
y

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

### Categorical

In [18]:
new_class = pd.Categorical(df['Pclas'])

In [20]:
new_class = new_class.rename_categories(['A','B','C'])

In [21]:
new_class

['A', 'B', 'C', 'A', 'B']
Categories (3, object): ['A', 'B', 'C']

## np.where gives the integer position 

In [24]:
missing = np.where(df['FlightNumber'].isnull() == True)

In [25]:
missing

(array([1, 3], dtype=int64),)