**Different scaling technique**

## sklearn.preprocessing.MinMaxScaler¶

Transform features by scaling each feature to a given range.
This estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one.
The transformation is given by:
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min


fit(X[, y]) : Compute the minimum and maximum to be used for later scaling.
fit_transform(X[, y]) : Fit to data, then transform it.


## sklearn.preprocessing.RobustScaler¶

This Scaler removes the median and scales the data according to the quantile range (defaults to IQR: Interquartile Range). The IQR is the range between the 1st quartile (25th quantile) and the 3rd quartile (75th quantile).
Centering and scaling happen independently on each feature by computing the relevant statistics on the samples in the training set. Median and interquartile range are then stored to be used on later data using the transform method.
Standardization of a dataset is a common requirement for many machine learning estimators. Typically this is done by removing the mean and scaling to unit variance. However, outliers can often influence the sample mean / variance in a negative way. 
In such cases, the median and the interquartile range often give better results.

fit(X[, y]) : Compute the median and quantiles to be used for scaling.
fit_transform(X[, y]) : Fit to data, then transform it.

## sklearn.preprocessing.StandardScaler¶

The standard score of a sample x is calculated as:
z = (x - u) / s
where u is the mean of the training samples or zero if with_mean=False, and s is the standard deviation of the training samples or one if with_std=False.


fit(X[, y]) : Compute the mean and std to be used for later scaling.
fit_transform(X[, y]) : Fit to data, then transform it.

In [1]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [2]:
import numpy as np

In [3]:
arr = np.array(data)

In [18]:
arr.reshape(2,4)

array([[0, 0, 0, 0],
       [1, 1, 1, 1]])

In [19]:
arr.mean()

0.5

In [20]:
arr.std()

0.5

In [22]:
arr2 = np.linspace(1,50,20)

In [30]:
arr2 = arr2.reshape(-1,2)

In [31]:
arr2

array([[ 1.        ,  3.57894737],
       [ 6.15789474,  8.73684211],
       [11.31578947, 13.89473684],
       [16.47368421, 19.05263158],
       [21.63157895, 24.21052632],
       [26.78947368, 29.36842105],
       [31.94736842, 34.52631579],
       [37.10526316, 39.68421053],
       [42.26315789, 44.84210526],
       [47.42105263, 50.        ]])

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
std_scaler = StandardScaler()

In [7]:
print(std_scaler.fit(data))

StandardScaler()


In [8]:
print(std_scaler.mean_)

[0.5 0.5]


In [24]:
print(std_scaler.transform(data))

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [38]:
print(std_scaler.fit_transform(arr2))

[[-1.5666989  -1.5666989 ]
 [-1.21854359 -1.21854359]
 [-0.87038828 -0.87038828]
 [-0.52223297 -0.52223297]
 [-0.17407766 -0.17407766]
 [ 0.17407766  0.17407766]
 [ 0.52223297  0.52223297]
 [ 0.87038828  0.87038828]
 [ 1.21854359  1.21854359]
 [ 1.5666989   1.5666989 ]]


In [10]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
mm_scaler = MinMaxScaler()

In [40]:
print(mm_scaler.fit(data))

MinMaxScaler()


In [41]:
print(mm_scaler.transform(data))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [42]:
print(mm_scaler.fit_transform(arr2))

[[0.         0.        ]
 [0.11111111 0.11111111]
 [0.22222222 0.22222222]
 [0.33333333 0.33333333]
 [0.44444444 0.44444444]
 [0.55555556 0.55555556]
 [0.66666667 0.66666667]
 [0.77777778 0.77777778]
 [0.88888889 0.88888889]
 [1.         1.        ]]


In [14]:
from sklearn.preprocessing import RobustScaler

In [15]:
Rb_scaler = RobustScaler()

In [16]:
print(Rb_scaler.fit(data))

RobustScaler()


In [17]:
print(Rb_scaler.transform(data))

[[-0.5 -0.5]
 [-0.5 -0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]]
